# test-related stuff, but it doesn't need to run on every os/version of python
name: Generate metadata

on:
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install App
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
        pip install mypy
        python setup.py install

    - name: Type-check
      run: mypy tabcmd tests

    - name: Check formatting with black
      run: black --line-length 120 tabcmd tests --check

